// app/layout.tsx

import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "My Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        {/* {children} chính là file page.tsx của bạn */}
        {children}
      </body>
    </html>
  );
}